import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { SendFeedbackButton } from "@/components/SendFeedbackButton";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-dvh bg-[#FAFAF9] text-[#18181B] antialiased">{children}
        <SendFeedbackButton appName="PocketSteak Recipes" endpointUrl="https://baseball-betting-app.vercel.app/api/send-feedback" />
      </body>
    </html>
  );
}
